name: example
description: raylib dart examples.
version: 1.0.0

publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  raylib:
    path: ../

dev_dependencies:
  very_good_analysis: ^2.4.0
